# Generated by Django 4.0.4 on 2022-05-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_singers_song_singer_song_owner_review_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='song',
        ),
    ]
