# Generated by Django 4.0.4 on 2022-06-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
    ]
